name: Publish to Hostinger

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs: 
      frontend-image: ghcr.io/${{github.repository_owner.toLower()}}/eventlamp-fe:latest
      backend-image: ghcr.io/${{github.repository_owner.toLower()}}/eventlamp-be:latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GHCR_PAT}}

      - name: Build Frontend Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner.toLower() }}/eventlamp-fe:latest ./Frontend

      - name: Build Backend Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner.toLower() }}/eventlamp-be:latest ./Backend

      - name: Push Frontend Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner.toLower() }}/eventlamp-fe:latest

      - name: Push Backend Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner.toLower() }}/eventlamp-backend:latest

          

      
